// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-F4Ztrnzqs-gLQhtcX0IT_jljKnPphQ',
    appId: '1:675159254100:web:3080ed5a0450377e7779c1',
    messagingSenderId: '675159254100',
    projectId: 'noteapp-2b7aa',
    authDomain: 'noteapp-2b7aa.firebaseapp.com',
    storageBucket: 'noteapp-2b7aa.appspot.com',
    measurementId: 'G-YZSKD2S2HT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl0aZkF78tW9YklauWddvJUYcLEkGaPhw',
    appId: '1:675159254100:android:083c4dc128a483ac7779c1',
    messagingSenderId: '675159254100',
    projectId: 'noteapp-2b7aa',
    storageBucket: 'noteapp-2b7aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnWOfYmHRmop46LRrTXYxqyDNALe-grow',
    appId: '1:675159254100:ios:95775ab708826ef07779c1',
    messagingSenderId: '675159254100',
    projectId: 'noteapp-2b7aa',
    storageBucket: 'noteapp-2b7aa.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnWOfYmHRmop46LRrTXYxqyDNALe-grow',
    appId: '1:675159254100:ios:82da0117cb5a8caf7779c1',
    messagingSenderId: '675159254100',
    projectId: 'noteapp-2b7aa',
    storageBucket: 'noteapp-2b7aa.appspot.com',
    iosBundleId: 'com.example.noteapp.RunnerTests',
  );
}
